name: Weekly blog and website report

on:
  schedule:
    - cron: '0 4 * * WED'  # Run at 04:00 UTC every Wednesday
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    if: github.repository == 'leanprover-community/mathlib4'

    steps:
    - name: Checkout website
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: 'leanprover-community/leanprover-community.github.io'
        path: website

    - name: Checkout blog
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: 'leanprover-community/leanprover-community.github.io'
        path: blog

    - name: Produce tables
      id: tables
      run: |
        for site in website blog
        do
          printf 'PRs in %s\n' "${site}"
          cd "${site}"
          printf $'%s<<EOF\n%s\nEOF' "${site}" "$(./scripts/formatGhPrList.sh "${site}")" | tee "$GITHUB_OUTPUT"
          cd ..
        done

    - name: Post output to Zulip
      uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
      with:
        api-key: ${{ secrets.ZULIP_API_KEY }}
        email: 'github-mathlib4-bot@leanprover.zulipchat.com'
        organization-url: 'https://leanprover.zulipchat.com'
        to: 'mathlib reviewers'
        type: 'stream'
        topic: 'blog and website PRs'
        content: |
          ###  Open website PRs

          ${{ steps.tables.outputs.website }}

          ###  Open blog PRs

          ${{ steps.tables.outputs.table }}
